name: Run Danger on PR

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  statuses: write

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.repository == 'facebook/react-native'
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm and Node.js
        uses: ./.github/actions/pnpm-setup-node
      - name: Install dependencies
        uses: ./.github/actions/pnpm-install
      - name: Run diff-js-api-breaking-changes
        uses: ./.github/actions/diff-js-api-breaking-changes
      - name: Danger
        run: pnpm exec danger ci --use-github-checks --failOnErrors
        working-directory: private/react-native-bots
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.REACT_NATIVE_BOT_GITHUB_TOKEN }}
